// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHABnM6rY-9sLPzgVKScZmvSZ8lUfUhfw',
    appId: '1:683550110929:web:3e108ea123c770dc8381f0',
    messagingSenderId: '683550110929',
    projectId: 'crm-payroll',
    authDomain: 'crm-payroll.firebaseapp.com',
    storageBucket: 'crm-payroll.firebasestorage.app',
    measurementId: 'G-4F48C8Q9XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGghMzDzxCgy-Vqeqg44AejeaHCiTUtXE',
    appId: '1:683550110929:android:3e108ea123c770dc8381f0',
    messagingSenderId: '683550110929',
    projectId: 'crm-payroll',
    storageBucket: 'crm-payroll.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO2GQRxFUDt-yIRdumEcuW8ACzI0EIMDA',
    appId: '1:683550110929:ios:3e108ea123c770dc8381f0',
    messagingSenderId: '683550110929',
    projectId: 'crm-payroll',
    storageBucket: 'crm-payroll.firebasestorage.app',
    iosBundleId: 'com.matcrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO2GQRxFUDt-yIRdumEcuW8ACzI0EIMDA',
    appId: '1:683550110929:ios:3e108ea123c770dc8381f0',
    messagingSenderId: '683550110929',
    projectId: 'crm-payroll',
    storageBucket: 'crm-payroll.firebasestorage.app',
    iosBundleId: 'com.matcrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHABnM6rY-9sLPzgVKScZmvSZ8lUfUhfw',
    appId: '1:683550110929:web:3e108ea123c770dc8381f0',
    messagingSenderId: '683550110929',
    projectId: 'crm-payroll',
    authDomain: 'crm-payroll.firebaseapp.com',
    storageBucket: 'crm-payroll.firebasestorage.app',
    measurementId: 'G-4F48C8Q9XZ',
  );
}
