// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDYAZJmMOC8zv3ZgKCO9EYQb65eNBmyFFc',
//     appId: '1:357274844337:web:86fac1c3eed3b34812f690',
//     messagingSenderId: '357274844337',
//     projectId: 'crm-notifications-bf781',
//     authDomain: 'crm-notifications-bf781.firebaseapp.com',
//     databaseURL: 'https://crm-notifications-bf781-default-rtdb.firebaseio.com',
//     storageBucket: 'crm-notifications-bf781.firebasestorage.app',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyA_YGQtOwItpeHcBzktl5lg9tq0AtcXlH8',
//     appId: '1:357274844337:android:6fb14d5c5ff59fc112f690',
//     messagingSenderId: '357274844337',
//     projectId: 'crm-notifications-bf781',
//     databaseURL: 'https://crm-notifications-bf781-default-rtdb.firebaseio.com',
//     storageBucket: 'crm-notifications-bf781.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBezsJGKUdnGtiexpwlPSC9tQfTwTuROY0',
//     appId: '1:357274844337:ios:1089ca4c485b07af12f690',
//     messagingSenderId: '357274844337',
//     projectId: 'crm-notifications-bf781',
//     databaseURL: 'https://crm-notifications-bf781-default-rtdb.firebaseio.com',
//     storageBucket: 'crm-notifications-bf781.firebasestorage.app',
//     iosBundleId: 'com.example.crmMilanCreations',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBezsJGKUdnGtiexpwlPSC9tQfTwTuROY0',
//     appId: '1:357274844337:ios:1089ca4c485b07af12f690',
//     messagingSenderId: '357274844337',
//     projectId: 'crm-notifications-bf781',
//     databaseURL: 'https://crm-notifications-bf781-default-rtdb.firebaseio.com',
//     storageBucket: 'crm-notifications-bf781.firebasestorage.app',
//     iosBundleId: 'com.example.crmMilanCreations',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDYAZJmMOC8zv3ZgKCO9EYQb65eNBmyFFc',
//     appId: '1:357274844337:web:19a372c078b1c48312f690',
//     messagingSenderId: '357274844337',
//     projectId: 'crm-notifications-bf781',
//     authDomain: 'crm-notifications-bf781.firebaseapp.com',
//     databaseURL: 'https://crm-notifications-bf781-default-rtdb.firebaseio.com',
//     storageBucket: 'crm-notifications-bf781.firebasestorage.app',
//   );
// }
